[2021-11-01 03:31:46,113] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.createTable manual__2021-11-01T03:31:42.418479+00:00 [queued]>
[2021-11-01 03:31:46,125] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.createTable manual__2021-11-01T03:31:42.418479+00:00 [queued]>
[2021-11-01 03:31:46,125] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 03:31:46,125] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-01 03:31:46,126] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 03:31:46,140] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): createTable> on 2021-11-01 03:31:42.418479+00:00
[2021-11-01 03:31:46,143] {standard_task_runner.py:52} INFO - Started process 92 to run task
[2021-11-01 03:31:46,146] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'createTable', 'manual__2021-11-01T03:31:42.418479+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/checkModel.py', '--cfg-path', '/tmp/tmpck6iif5s', '--error-file', '/tmp/tmpoc8l7gkk']
[2021-11-01 03:31:46,146] {standard_task_runner.py:77} INFO - Job 123: Subtask createTable
[2021-11-01 03:31:46,176] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.createTable manual__2021-11-01T03:31:42.418479+00:00 [running]> on host e4a42aadf2ec
[2021-11-01 03:31:46,211] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=createTable
AIRFLOW_CTX_EXECUTION_DATE=2021-11-01T03:31:42.418479+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-01T03:31:42.418479+00:00
[2021-11-01 03:31:46,291] {python.py:152} INFO - Done. Returned value was: None
[2021-11-01 03:31:46,300] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=createTable, execution_date=20211101T033142, start_date=20211101T033146, end_date=20211101T033146
[2021-11-01 03:31:46,357] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-01 03:31:46,423] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
