[2021-11-01 00:56:22,208] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:56:20.149617+00:00 [queued]>
[2021-11-01 00:56:22,222] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:56:20.149617+00:00 [queued]>
[2021-11-01 00:56:22,223] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 00:56:22,223] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-01 00:56:22,223] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 00:56:22,231] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): also_run_this> on 2021-11-01 00:56:20.149617+00:00
[2021-11-01 00:56:22,235] {standard_task_runner.py:52} INFO - Started process 1290 to run task
[2021-11-01 00:56:22,237] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'also_run_this', 'manual__2021-11-01T00:56:20.149617+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/checkModel.py', '--cfg-path', '/tmp/tmpro3d4djf', '--error-file', '/tmp/tmpsbznbmgs']
[2021-11-01 00:56:22,238] {standard_task_runner.py:77} INFO - Job 24: Subtask also_run_this
[2021-11-01 00:56:22,266] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:56:20.149617+00:00 [running]> on host 7b304be9cff3
[2021-11-01 00:56:22,300] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-11-01T00:56:20.149617+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-01T00:56:20.149617+00:00
[2021-11-01 00:56:22,301] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-01 00:56:22,301] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pwd']
[2021-11-01 00:56:22,310] {subprocess.py:85} INFO - Output:
[2021-11-01 00:56:22,311] {subprocess.py:89} INFO - /tmp/***tmp_lw0_4_l
[2021-11-01 00:56:22,312] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-01 00:56:22,329] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=also_run_this, execution_date=20211101T005620, start_date=20211101T005622, end_date=20211101T005622
[2021-11-01 00:56:22,369] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-01 00:56:22,392] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
