[2021-11-01 00:57:11,956] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:57:10.239790+00:00 [queued]>
[2021-11-01 00:57:11,968] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:57:10.239790+00:00 [queued]>
[2021-11-01 00:57:11,968] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 00:57:11,968] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-01 00:57:11,968] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 00:57:11,977] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): also_run_this> on 2021-11-01 00:57:10.239790+00:00
[2021-11-01 00:57:11,981] {standard_task_runner.py:52} INFO - Started process 1335 to run task
[2021-11-01 00:57:11,984] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'also_run_this', 'manual__2021-11-01T00:57:10.239790+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/checkModel.py', '--cfg-path', '/tmp/tmp6z7o_l31', '--error-file', '/tmp/tmp_fnu7e_m']
[2021-11-01 00:57:11,984] {standard_task_runner.py:77} INFO - Job 26: Subtask also_run_this
[2021-11-01 00:57:12,012] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.also_run_this manual__2021-11-01T00:57:10.239790+00:00 [running]> on host 7b304be9cff3
[2021-11-01 00:57:12,049] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-11-01T00:57:10.239790+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-01T00:57:10.239790+00:00
[2021-11-01 00:57:12,049] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-01 00:57:12,050] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'ls']
[2021-11-01 00:57:12,059] {subprocess.py:85} INFO - Output:
[2021-11-01 00:57:12,061] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-01 00:57:12,081] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=also_run_this, execution_date=20211101T005710, start_date=20211101T005711, end_date=20211101T005712
[2021-11-01 00:57:12,115] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-01 00:57:12,138] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
