[2021-11-01 03:23:03,928] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.createTable manual__2021-11-01T03:23:02.029480+00:00 [queued]>
[2021-11-01 03:23:03,936] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.createTable manual__2021-11-01T03:23:02.029480+00:00 [queued]>
[2021-11-01 03:23:03,936] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 03:23:03,936] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-01 03:23:03,936] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-01 03:23:03,950] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): createTable> on 2021-11-01 03:23:02.029480+00:00
[2021-11-01 03:23:03,953] {standard_task_runner.py:52} INFO - Started process 82 to run task
[2021-11-01 03:23:03,955] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'createTable', 'manual__2021-11-01T03:23:02.029480+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/checkModel.py', '--cfg-path', '/tmp/tmpx26k08hy', '--error-file', '/tmp/tmpzt1xhgms']
[2021-11-01 03:23:03,956] {standard_task_runner.py:77} INFO - Job 115: Subtask createTable
[2021-11-01 03:23:03,983] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.createTable manual__2021-11-01T03:23:02.029480+00:00 [running]> on host 93c37aa78767
[2021-11-01 03:23:04,018] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=createTable
AIRFLOW_CTX_EXECUTION_DATE=2021-11-01T03:23:02.029480+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-01T03:23:02.029480+00:00
[2021-11-01 03:23:04,088] {python.py:152} INFO - Done. Returned value was: None
[2021-11-01 03:23:04,117] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=createTable, execution_date=20211101T032302, start_date=20211101T032303, end_date=20211101T032304
[2021-11-01 03:23:04,167] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-01 03:23:04,230] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
